name: ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm astro check

      - name: Build
        run: pnpm build

      - name: Check internal links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --offline --root-dir ${{ github.workspace }}/dist --include-fragments dist
          fail: true
